"""
Stage B — Decompose each generated_answer into atomic claims.
Prompt is FIXED per PROJECT_PLAN.md Section 4.1. Do not edit inline;
if you must change it, log the change with a timestamp in
notes/prompt_changes.md and note which results used which version.

Retry rule: if parsing fails or returns < 1 claim, retry once at
temperature 0. If it fails again, mark decomposition_failed=True and
log the example id — do NOT silently drop it from the record.
"""
import json
import os
import re
import ollama

CLAIM_PROMPT = """You will be given a question and an answer generated by an AI system. Break the answer down into a list of atomic factual claims. Each claim must be a single, independently checkable statement. Do not include claims that are purely opinion, hedging language ("it seems"), or meta-commentary about the answer itself. Output ONLY a JSON list of strings, nothing else.

Question: {question}
Answer: {generated_answer}

Output format: ["claim 1", "claim 2", ...]"""

CACHE_DIR = "data/claims"


def _extract_json_list(text):
    """Best-effort extraction of a JSON list from model output that may
    include stray text around it."""
    match = re.search(r"\[.*\]", text, re.DOTALL)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
        if isinstance(parsed, list) and all(isinstance(x, str) for x in parsed):
            return parsed
    except json.JSONDecodeError:
        return None
    return None


def decompose_claims(example_id, question, generated_answer, model="llama3.1"):
    cache_path = os.path.join(CACHE_DIR, f"{example_id}.json")
    if os.path.exists(cache_path):
        with open(cache_path) as f:
            return json.load(f)

    prompt = CLAIM_PROMPT.format(question=question, generated_answer=generated_answer)

    response = ollama.chat(model=model, messages=[{"role": "user", "content": prompt}])
    claims = _extract_json_list(response["message"]["content"])

    if not claims:
        # retry once at temperature 0
        response = ollama.chat(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0},
        )
        claims = _extract_json_list(response["message"]["content"])

    result = {
        "id": example_id,
        "claims": claims if claims else [],
        "decomposition_failed": claims is None,
    }

    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(cache_path, "w") as f:
        json.dump(result, f, indent=2)

    return result


if __name__ == "__main__":
    from data_loader import load_examples

    examples = load_examples()
    failures = 0
    for ex in examples[:5]:  # test on 5 first, per Section 9 schedule
        result = decompose_claims(ex["id"], ex["question"], ex["generated_answer"])
        print(f"{ex['id']}: {len(result['claims'])} claims, failed={result['decomposition_failed']}")
        if result["decomposition_failed"]:
            failures += 1
    print(f"\n{failures}/5 decomposition failures in test batch.")
